//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class App
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public int DevelopmentRequestId { get; set; }
        public int SystemId { get; set; }
        public int SoftwarePackageId { get; set; }
        public int DeveloperId { get; set; }
    
        public virtual DevelopmentRequest DevelopmentRequest { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual SoftwarePackage SoftwarePackage { get; set; }
        public virtual SAOSystem System { get; set; }
    }
}
