//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeployPackageEvent
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Notes { get; set; }
        public int Deployment { get; set; }
    
        public virtual Deployment Deployment1 { get; set; }
    }
}
