//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deployment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deployment()
        {
            this.DeployPackageEvents = new HashSet<DeployPackageEvent>();
        }
    
        public int Id { get; set; }
        public int EnvironmentToId { get; set; }
        public int DeployPackageId { get; set; }
        public string Status { get; set; }
        public string DeployedBy { get; set; }
        public Nullable<System.DateTime> DeployedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual DeployEnvironment EnvironmentTo { get; set; }
        public virtual DeployPackage DeployPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeployPackageEvent> DeployPackageEvents { get; set; }
    }
}
