//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevelopmentRequestHour
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int EstHours { get; set; }
        public int CompletedHours { get; set; }
        public string Notes { get; set; }
        public int DevelopmentRequest { get; set; }
    
        public virtual DevelopmentRequest DevelopmentRequest1 { get; set; }
    }
}
