//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int Id { get; set; }
        public string Summary { get; set; }
        public string RaisedBy { get; set; }
        public string Priority { get; set; }
        public string ResolutionNotes { get; set; }
        public string StatusNotes { get; set; }
        public Nullable<System.DateTime> RasiedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public int SystemId { get; set; }
        public Nullable<int> DeveloperId { get; set; }
        public int RequestStatusId { get; set; }
        public Nullable<int> DevelopmentRequestId { get; set; }
        public Nullable<int> IssueTypeId { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual DevelopmentRequest DevelopmentRequest { get; set; }
        public virtual IssueType IssueType { get; set; }
        public virtual RequestStatusSet RequestStatusSet { get; set; }
        public virtual SAOSystem System { get; set; }
    }
}
