//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedSSRSReport
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public System.Guid SSRSReportId { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
