//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSpecHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportSpecHeader()
        {
            this.ReportSpecDataSelections = new HashSet<ReportSpecDataSelection>();
            this.ReportSpecFilters = new HashSet<ReportSpecFilter>();
            this.ReportSpecParameters = new HashSet<ReportSpecParameter>();
            this.ReportSpecSourceDatas = new HashSet<ReportSpecSourceData>();
        }
    
        public int Id { get; set; }
        public string ReportName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PreparedBy { get; set; }
        public string BusinessArea { get; set; }
        public string ReportType { get; set; }
        public string ReportingTool { get; set; }
        public string BusinessOwner { get; set; }
        public string BusinessPurpose { get; set; }
        public string StdVsAdHocDesc { get; set; }
        public bool RequiresWorldData { get; set; }
        public string RequiresWorldDataNotes { get; set; }
        public bool RequiresLocalDataStorage { get; set; }
        public string RequiresLocalDataStorageNotes { get; set; }
        public bool RequiresApplicationInterface { get; set; }
        public string RequiresApplicationInterfaceNotes { get; set; }
        public string GroupOrderByDesc { get; set; }
        public string SubTotalSummaryDesc { get; set; }
        public string Notes { get; set; }
        public bool OnDemmandDelivery { get; set; }
        public string OnDemmandDeliveryNotes { get; set; }
        public bool EmailSubscription { get; set; }
        public string EmailSubscriptionNotes { get; set; }
        public bool ExcelDataConnection { get; set; }
        public string ExcelDataConnectionNotes { get; set; }
        public bool LiveDashboard { get; set; }
        public string LiveDashboardNotes { get; set; }
        public Nullable<int> SoftwarePackageId { get; set; }
        public Nullable<int> DevRequestId { get; set; }
    
        public virtual DevelopmentRequest DevelopmentRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSpecDataSelection> ReportSpecDataSelections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSpecFilter> ReportSpecFilters { get; set; }
        public virtual SoftwarePackage SoftwarePackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSpecParameter> ReportSpecParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSpecSourceData> ReportSpecSourceDatas { get; set; }
    }
}
