//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSpecDataSelection
    {
        public int Id { get; set; }
        public string FieldName { get; set; }
        public string TableName { get; set; }
        public string SourceFieldName { get; set; }
        public string CalculatedField { get; set; }
        public int ReportSpecificationId { get; set; }
    
        public virtual ReportSpecHeader ReportSpecHeader { get; set; }
    }
}
