//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.LinkedSSRSReports = new HashSet<LinkedSSRSReport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public int DeveloperId { get; set; }
        public Nullable<int> DevelopmentRequestId { get; set; }
        public int SystemId { get; set; }
        public int SoftwarePackageId { get; set; }
        public System.Guid SSRSId { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual DevelopmentRequest DevelopmentRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkedSSRSReport> LinkedSSRSReports { get; set; }
        public virtual SoftwarePackage SoftwarePackage { get; set; }
        public virtual SAOSystem System { get; set; }
    }
}
