//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevManager.WebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemDepartment
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int SystemId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual SAOSystem System { get; set; }
    }
}
